[package]
name = "sagittarius"
version = "0.1.0"
edition = "2024"

[dependencies]
input = "0.9"
evdev = "0.12"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = "2.10"
dotenv = "0.15.0"
